# Generated by Django 6.0.4 on 2026-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='morning_summary',
            field=models.BooleanField(default=True, verbose_name='Утренняя сводка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='morning_summary_time',
            field=models.TimeField(default='08:00', verbose_name='Время утренней сводки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reminder_before_task',
            field=models.IntegerField(default=30, verbose_name='Напоминание до задачи (минут)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Аватар'),
        ),
    ]
